CREATE TYPE "visibility_enum" AS ENUM (
	'public',
	'private',
	'unlisted'
);

CREATE TYPE "quiz_type_enum" AS ENUM (
	'single',
	'multiple'
);

CREATE TYPE "role_enum" AS ENUM (
	'user',
	'admin',
	'super admin'
);

CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"username" VARCHAR(20) NOT NULL UNIQUE,
	"name" VARCHAR(50) NOT NULL,
	"email" TEXT NOT NULL UNIQUE,
	"email_verified_at" TIMESTAMP DEFAULT null,
	"password" VARCHAR(255) NOT NULL,
	"role" ROLE_ENUM NOT NULL,
	"two_factor_secret" TEXT DEFAULT null,
	"two_factor_recovery_codes" TEXT DEFAULT null,
	"two_factor_confirmed_at" TIMESTAMP DEFAULT null,
	"remember_token" VARCHAR(100) DEFAULT null,
	"created_at" TIMESTAMP DEFAULT null,
	"updated_at" TIMESTAMP DEFAULT null,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "quizzes" (
	"id" UUID NOT NULL,
	"user_id" INTEGER NOT NULL,
	"name" VARCHAR(100) NOT NULL,
	"description" TEXT DEFAULT null,
	-- average rating
	"average_rating" NUMERIC(4,3) DEFAULT null,
	-- Sum of all ratings. For example, if two users give a rating of 5, the total is 10
	"rating_sum" INTEGER DEFAULT null,
	-- Total users who have rated
	"rating_count" INTEGER DEFAULT null,
	"category" VARCHAR(255) DEFAULT null,
	"visibility" VISIBILITY_ENUM NOT NULL,
	"quiz_type" QUIZ_TYPE_ENUM NOT NULL,
	"randomize_question" BOOLEAN NOT NULL DEFAULT false,
	"randomize_answer" BOOLEAN NOT NULL DEFAULT false,
	"leason material" TEXT ARRAY DEFAULT null,
	"ai_learning_feature" BOOLEAN NOT NULL DEFAULT false,
	"comment_count" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP DEFAULT null,
	"updated_at" TIMESTAMP DEFAULT null,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "quizzes"."average_rating" IS 'average rating';
COMMENT ON COLUMN "quizzes"."rating_sum" IS 'Sum of all ratings. For example, if two users give a rating of 5, the total is 10';
COMMENT ON COLUMN "quizzes"."rating_count" IS 'Total users who have rated';


CREATE TABLE IF NOT EXISTS "comments" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"quiz_id" UUID NOT NULL,
	"leaderboard_id" INTEGER NOT NULL,
	"comment" TEXT NOT NULL,
	"created_at" TIMESTAMP DEFAULT null,
	"updated_at" TIMESTAMP DEFAULT null,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "leaderboards" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"quiz_id" UUID NOT NULL,
	"score" INTEGER NOT NULL DEFAULT 0,
	-- second
	"attempt_duration_seconds" INTEGER NOT NULL DEFAULT 0,
	"attempt_number" INTEGER NOT NULL DEFAULT 0,
	"leave_count" SMALLINT NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP DEFAULT null,
	"updated_at" TIMESTAMP DEFAULT null,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "leaderboards"."attempt_duration_seconds" IS 'second';


CREATE TABLE IF NOT EXISTS "quiz_questions" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"quiz_id" UUID NOT NULL,
	"question" TEXT NOT NULL,
	"question_image" TEXT ARRAY DEFAULT null,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "quiz_answers" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"quiz_question_id" INTEGER NOT NULL,
	"answer" TEXT NOT NULL,
	"answer_image" TEXT ARRAY DEFAULT null,
	"is_correct" BOOLEAN NOT NULL DEFAULT false,
	"created_at" TIMESTAMP DEFAULT null,
	"updated_at" TIMESTAMP DEFAULT null,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "quiz_user_answers" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"quiz_question_answer_id" INTEGER NOT NULL,
	"leaderboard_id" INTEGER NOT NULL,
	"answer" INTEGER ARRAY,
	"leave_count" INTEGER NOT NULL DEFAULT 0,
	"attempt_duration_seconds" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP DEFAULT null,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "logs" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	-- max char uuid with hyphens = 36
	-- max char integer = 10
	"affected_id" VARCHAR(40) NOT NULL,
	"related_table" VARCHAR(255) NOT NULL,
	"action" VARCHAR(255) NOT NULL,
	"description" TEXT NOT NULL,
	"created_at" TIMESTAMP DEFAULT null,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "logs"."affected_id" IS 'max char uuid with hyphens = 36
max char integer = 10';


CREATE TABLE IF NOT EXISTS "cache" (
	"key" VARCHAR(255) NOT NULL,
	"value" TEXT NOT NULL,
	"expiration" BIGINT NOT NULL,
	PRIMARY KEY("key")
);


CREATE INDEX "cache_index_0"
ON "cache" ("expiration");

CREATE TABLE IF NOT EXISTS "cache_locks" (
	"key" VARCHAR(255) NOT NULL,
	"owner" VARCHAR(255) NOT NULL,
	"expiration" BIGINT NOT NULL,
	PRIMARY KEY("key")
);


CREATE INDEX "cache_locks_index_0"
ON "cache_locks" ("expiration");

CREATE TABLE IF NOT EXISTS "failed_jobs" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"uuid" VARCHAR(255) NOT NULL,
	"connection" VARCHAR(255) NOT NULL,
	"queue" VARCHAR(255) NOT NULL,
	"payload" TEXT NOT NULL,
	"exception" TEXT NOT NULL,
	"failed_at" TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY("id")
);


CREATE INDEX "failed_jobs_index_0"
ON "failed_jobs" ("uuid", "connection", "queue", "failed_at");

CREATE TABLE IF NOT EXISTS "jobs" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"queue" VARCHAR(255) NOT NULL,
	"payload" TEXT NOT NULL,
	"attempts" SMALLINT NOT NULL,
	"reserved_at" INTEGER DEFAULT null,
	"available_at" INTEGER NOT NULL,
	"created_at" INTEGER NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "jobs_index_0"
ON "jobs" ("queue");

CREATE TABLE IF NOT EXISTS "job_batches" (
	"id" VARCHAR(255) NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"total_jobs" INTEGER NOT NULL,
	"pending_jobs" INTEGER NOT NULL,
	"failed_jobs" INTEGER NOT NULL,
	"failed_job_ids" TEXT NOT NULL,
	"options" TEXT DEFAULT null,
	"cancelled_at" INTEGER DEFAULT null,
	"created_at" INTEGER NOT NULL,
	"finished_at" INTEGER DEFAULT null,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "migrations" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"migration" VARCHAR(255) NOT NULL,
	"batch" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
	"email" VARCHAR(255) NOT NULL,
	"token" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP DEFAULT null,
	PRIMARY KEY("email")
);




CREATE TABLE IF NOT EXISTS "sessions" (
	"id" VARCHAR(255) NOT NULL,
	"user_id" BIGINT DEFAULT null,
	"ip_address" VARCHAR(45) DEFAULT null,
	"user_agent" TEXT DEFAULT null,
	"payload" TEXT NOT NULL,
	"last_activity" INTEGER NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "sessions_index_0"
ON "sessions" ("user_id", "last_activity");
ALTER TABLE "quizzes"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "comments"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "comments"
ADD FOREIGN KEY("quiz_id") REFERENCES "quizzes"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "leaderboards"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "leaderboards"
ADD FOREIGN KEY("quiz_id") REFERENCES "quizzes"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "quiz_questions"
ADD FOREIGN KEY("quiz_id") REFERENCES "quizzes"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "quiz_user_answers"
ADD FOREIGN KEY("quiz_question_answer_id") REFERENCES "quiz_questions"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "quiz_user_answers"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "quiz_user_answers"
ADD FOREIGN KEY("leaderboard_id") REFERENCES "leaderboards"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "quiz_answers"
ADD FOREIGN KEY("quiz_question_id") REFERENCES "quiz_questions"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "logs"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE CASCADE ON DELETE SET NULL;